all:
	gcc -Wall -Werror -Wextra -std=c99 -pedantic assignment.c -o assignment -g
	./assignment

echo: 
	gcc -Wall -Werror -Wextra -std=c99 -pedantic echo.c -o echo -g
	./echo

clean:
	$(rm) echo

.PHONY: all echo clean
